export default {
    GRAY: '#F0F0F0',
    DARK_GRAY: '#2F3B5E',
    MID_GRAY: '#565D7C',
    LIGHT_GRAY: '#646B82',
    DARK_RED: '#FF0A2A',
    DEEP_RED: 'darkred',
    MID_RED: '#FF2F41',
    LIGHT_RED: '#FF5962',
    WHITE: '#FFFFFF',
    BLACK: '#000000',
    LIGHT_YELLOW: '#FFE9D8',
    DARK_YELLOW: '#FFD8BA',
    BLUE: "#65A3F0",
    TRANSPARENT: 'transparent',
    INVALID_TEXT: '#e0e0e0',
};